name: Deploy
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build master
      if: github.ref == 'refs/heads/master'
      uses: alvine998/admin_bengkelsehati@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          sudo branch=master /var/repo/nama-repository.git/hooks/post-receive